import { InspectorControls, RichText, URLInput, useBlockProps } from '@wordpress/block-editor';
import { Button, PanelBody, SelectControl, ToggleControl } from '@wordpress/components';

export default function Edit({ attributes, setAttributes }) {
    const { background = 'pale-blue', eyebrow, heading, text, showButton, buttonLabel, buttonUrl, gifts = [] } = attributes;
    const updateGift = (index, values) => setAttributes({ gifts: gifts.map((gift, giftIndex) => giftIndex === index ? { ...gift, ...values } : gift) });
    const sectionClass = `sb-scholarship-support sb-block-bg alignfull${background !== 'white' ? ` sb-block-bg--${background}` : ''}`;
    const blockProps = useBlockProps({ className: sectionClass });
    return <>
        <InspectorControls><PanelBody title="Scholarship support settings"><SelectControl label="Background color" value={background} options={[{ label: 'White', value: 'white' }, { label: 'Pale blue', value: 'pale-blue' }, { label: 'Dark blue', value: 'dark-blue' }]} onChange={(value) => setAttributes({ background: value })} /><ToggleControl label="Show donation button" checked={showButton} onChange={(value) => setAttributes({ showButton: value })} />{showButton && <><p className="sb-editor-field-label">Button link</p><URLInput value={buttonUrl} onChange={(value) => setAttributes({ buttonUrl: value })} /></>}</PanelBody></InspectorControls>
        <section {...blockProps}><div className="sb-container sb-scholarship-support__grid"><div><RichText tagName="p" className="sb-eyebrow" value={eyebrow} placeholder="Eyebrow" onChange={(value) => setAttributes({ eyebrow: value })} /><RichText tagName="h2" value={heading} allowedFormats={['core/bold', 'core/italic', 'soundbridge/pale-blue-highlight']} placeholder="Support heading" onChange={(value) => setAttributes({ heading: value })} /><RichText tagName="p" className="sb-scholarship-support__copy" value={text} placeholder="Support description" onChange={(value) => setAttributes({ text: value })} />{showButton && <RichText tagName="span" className="sb-btn" value={buttonLabel} allowedFormats={[]} placeholder="Button label" onChange={(value) => setAttributes({ buttonLabel: value })} />}</div><div className="sb-scholarship-gifts">{gifts.map((gift, index) => <div className="sb-scholarship-gift" key={index}><div className="sb-scholarship-gift__controls"><Button label="Remove gift example" isDestructive onClick={() => setAttributes({ gifts: gifts.filter((_, giftIndex) => giftIndex !== index) })} size="small"><span className="dashicons dashicons-trash" /></Button></div><RichText tagName="strong" value={gift.amount} allowedFormats={[]} placeholder="$25" onChange={(value) => updateGift(index, { amount: value })} /><RichText tagName="span" value={gift.description} placeholder="Giving impact" onChange={(value) => updateGift(index, { description: value })} /></div>)}</div></div><div className="sb-container"><Button className="sb-scholarship-support__add" variant="secondary" onClick={() => setAttributes({ gifts: [...gifts, { amount: '', description: '' }] })}><span className="dashicons dashicons-plus" />Add gift example</Button></div></section>
    </>;
}
